### ISSUE TITLE
[duckhee][#5F4B8B - 상품 빼기] 상품 재고 빼기

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#12]
- [기능]
	- 상품별 재고를 빼기 기능 구현
- [완료조건]
	- 재고 추가시 0개 미만일 경우 경고창 표시
	- 재고 뺄때 기존 재고량 표시
- [예상소요시간]
	- 2시간

**Comment by shldhee** [comment]
[완료시간]
1시간

**Comment by rosd89** [comment]
실패
