### ISSUE TITLE
[duckhee][#5F4B8B - 상품 진열 공간] 상품 진열 공간 만들기

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#13]
- [기능]
	- 상품이 진열 가능한 공간을 만든다. 배열로 만들어 저장하고 화면에 보여줄 때는 3주롤 표현
- [완료조건]
	- 상품 30개가 들어가게 만든다.
	- 30개 이상 등록시 경고창 표시
- [예상소요시간]
	- 2시간

**Comment by rosd89** [comment]
실패
