### ISSUE TITLE
[duckhee][#5F4B8B - 상품 진열 공간] 상품 옵션(ice, hot) 추가

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#16]
- [기능]
	- 고민중입니다.
- [완료조건]
	- 상품 상태에 ice, hot을 추가하고 표시한다.
	- 재고를 하나로 합칠지, 따로 상품을 뺼지 정해야 한다. 옵션별 재고 관리는 생각해보자.
- [예상소요시간]
	- 2시간

**Comment by rosd89** [comment]
실패
