### ISSUE TITLE
[duckhee][#5F4B8B - 자판기의 상태] 자판기 판매가능 유무

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#17]
- [기능]
	- 전체 재고가 0일때 판매 불가 상태로 변경
	- 자판기 전원이 ON, OFF로 구분하여 상태를 변경
- [완료조건]
	- 관리자 임의로 판매 불가 상태로 변경
	- 판매 불가시에는 버튼 불빛이 사라짐
- [예상소요시간]
	- 2시간

**Comment by rosd89** [comment]
실패
