### ISSUE TITLE
[duckhee][#5F4B8B - 상품 선택 버튼] 상품 선택 후 가격 비교

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#18]
- [기능]
	- 입력받은 재화보다 상품의 가격이 높을 경우 판매 불가
- [완료조건]
	- 입력받은 돈이 상품의 가격보다 적을때 버튼 사용 불가 처리
	- 버튼 클릭 시 경고창 표시
- [예상소요시간]
	- 2시간

**Comment by rosd89** [comment]
실패
