### ISSUE TITLE
[duckhee][#5F4B8B - 판매량 체크] 상품 별 판매량 확인

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#19]
- [기능]
	- 상품 별로 결제시 재고 감소할 때 체크할 판매 재고량을 만들어 관리
- [완료조건]
	- 상품별로 결제시에만 판매 재고로 잡히게 한다.
- [예상소요시간]
	- 2시간

**Comment by rosd89** [comment]
실패
