### ISSUE TITLE
[duckhee][#5F4B8B - 재화를 입력] 재화 구분하여 입력 받기

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#22]
- [기능]
	- 동전 입력란, 지폐 입력란 따로 만들어 받는다.
- [완료조건]
	- 동전인지 지폐인지 확인
	- 동전은 10원, 50원, 500원으로 확인
	- 지폐는 1000원, 5000원, 10000원, 50000원으로 확인
- [예상소요시간]
	- 4시간

**Comment by rosd89** [comment]
실패
