### ISSUE TITLE
[duckhee][#5F4B8B - 결제] 상품 선택할 때 재화 차감

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#23]
- [기능]
	- 상품 버튼 클릭시 재화가 상품가격만큼 차감
	- 화면에 표시
- [완료조건]
	- 상품 버튼 누를때 상품 1개 값을 차감
	- 남은 금액이 자판기에 보인다.
- [예상소요시간]
	- 2시간

**Comment by rosd89** [comment]
실패
