### ISSUE TITLE
[duckhee][#5F4B8B - 잔돈을 반환] 레버를 돌려 잔돈 반환

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#25]
- [기능]
	- 5초가 지나가기전에 수동으로 레버 버튼 누르면 잔돈을 반환
- [완료조건]
	- 5초전에 레버를 눌러 잔돈을 반환
- [예상소요시간]
	- 2시간

**Comment by rosd89** [comment]
실패
