### ISSUE TITLE
[duckhee][#5F4B8B - 잔돈을 반환] 자동으로 잔돈 반환

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#26]
- [기능]
	- 5초 동안 결제 및 다른 행동을 하지 않을 때 자동으로 잔돈 반환
- [완료조건]
	- 상품 선택 후 또는 돈을 넣은 뒤 5초동안 아무것도 하지 않으면 잔돈을 반환
- [예상소요시간]
	- 3시간

**Comment by rosd89** [comment]
실패
