### ISSUE TITLE
[duckhee][#5F4B8B - 잔돈을 반환] 결제 후 5초내 설정

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#27]
- [기능]
	- 결제 후 5초내로 돈을 다시 넣거나 상품을 클릭 후에는 잔돈 자동 반환이 5초로 갱신
- [완료조건]
	- 결제 후 5초내 돈을 넣으면 잔돈을 5초뒤에 반환
	- 결제 후 5초내 상품 결제하면 잔돈을 5초뒤에 반환
- [예상소요시간]
	- 3시간

**Comment by rosd89** [comment]
실패
