### ISSUE TITLE
[choiminji][#5F4B8B - 상품 등록] 등록 상품 관련 데이터베이스

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#28]
[기능] 데이터베이스에 상품을 등록하여 관련 정보 관리  

[소요시간] -

[완료조건]
상품 재고 데이터베이스 마련(javascript 배열 혹은 map으로 작업 예정)
[idx / 상품명 / 가격 / hot-ice / 재고량 / 출력여부]

**Comment by mmindy** [comment]
[실제 소요시간] 30분

**Comment by rosd89** [comment]
실패
