### ISSUE TITLE
[choiminji][#5F4B8B - 상품 등록] 상품 등록

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#29]
[기능] 상품을 등록하여 재고를 관리한다

[소요시간] 2시간

[완료조건]
상품 개수에는 제한이 없으나, 출력 상품의 경우 최대 30개 등록 가능
기존 등록된 상품명과 동일한 상품은 등록할 수 없으며,
상품명과 가격, hot-ice, 출력여부 등 각 요소들은 수정 가능

**Comment by mmindy** [comment]
[소요시간] 2시간 30분

**Comment by mmindy** [comment]
[소요시간] 4시간(2:30 +1:30 ),,

**Comment by mmindy** [comment]
[소요시간] 7시간(2:30 +1:30 +1:30+1:30)

하하하,,

**Comment by mmindy** [comment]
[소요시간] 9시간 30분(2:30 + 1:30 + 1:30 + 1:30 + 2:30)

**Comment by rosd89** [comment]
실패
