### ISSUE TITLE
[choiminji][#5F4B8B - 상품 등록] 상품 재고 없을 경우 등록 목록에서 삭제

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#30]
[기능] 상품의 재고량이 0일 경우, 상품 정보를 목록에서 삭제한다

[소요시간] 2시간

[완료조건]
관리자가 상품 빼어 상품의 재고량이 0일 때 상품 정보 삭제
사용자 결제로 재고량이 0될 경우, 삭제x
판매량 데이터베이스에 등록

**Comment by mmindy** [comment]
[소요시간] 3시간

**Comment by rosd89** [comment]
실패
