### ISSUE TITLE
 [choiminji][#5F4B8B - 상품 채우기] 재고 확인

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#31]
[기능] 각 상품별로 재고량을 확인할 수 있다

[소요시간] 30분

[완료조건]
상품별 재고량 확인 가능

**Comment by mmindy** [comment]
[소요시간] 1시간 

- #31 #35  #36  함께 작업(중복된 이슈)

**Comment by rosd89** [comment]
실패
