### ISSUE TITLE
[choiminji][#5F4B8B - 상품 빼기] 재고 상관없이 재고량 차감

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#34]
[기능] 기존 재고량 상관없이 재고량을 차감할 수 있다

[소요시간] 30분

[완료조건]
관리자는 재고량에 제한 없이 상품 뺄 수 있으며, 이때 재고량 0이 될 경우 상품 정보 삭제
판매량 데이터베이스에 등록

**Comment by mmindy** [comment]
#29 작업에서 충족

**Comment by rosd89** [comment]
실패
