### ISSUE TITLE
[choiminji][#5F4B8B - 재고 확인] 재고 관련 작업마다 재고 확인하여 진행

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#35]
[기능] 재고량 추가 및 차감 관련 모든 동작은 재고 확인하여 진행해야 한다

[소요시간] 1시간

[완료조건] 
재고량 변동 시마다 상품 재고량 수정(+/-). 재고 없을 경우 재고 표시만 반환
(최대값 30넘을 경우 재고 추가 불가 / 재고량 0일 경우 결제 불가 / 관리자가 상품 모두 뺄 경우 상품 정보 삭제)

**Comment by mmindy** [comment]
[소요시간] 1시간 

- #31 #35  #36  함께 작업(중복된 이슈)

**Comment by rosd89** [comment]
실패
