### ISSUE TITLE
 [choiminji][#5F4B8B - 재고 표시] 재고 변동에 따라 각 상품의 재고량 반환

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#36]
[기능] 상품의 변동에 따라 재고량을 반환한다

[소요시간] 30분

[완료조건]
재고량 변동 시마다 해당 상품 재고량 반환

**Comment by mmindy** [comment]
[소요시간] 1시간 

- #31 #35  #36  함께 작업(중복된 이슈)

**Comment by rosd89** [comment]
실패
