### ISSUE TITLE
 [choiminji][#5F4B8B - 판매량 체크] 일별 상품 판매량 기록

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#37]
[기능] 하루 동안 각 상품의 판매기록을 확인할 수 있다

[소요시간] 2시간

[완료조건] 
통계위한 데이터베이스 마련
- [idx / 상품명(혹은 상품idx) / 판매 및 재고빼간 수량 / 판매 or 관리 / 일자]
관리자가 상품 추가, 차감 시 + 사용자 상품 결제 시 데이터베이스에 등록

**Comment by rosd89** [comment]
실패
