### ISSUE TITLE
[choiminji][#5F4B8B - 상품 진열 공간] 3x10 규격의 진열 공간

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#38]
[기능] 3x10 규격의 진열 공간에 상품을 진열한다

[소요시간] 30분

[완료조건] 
등록순으로 출력여부에 체크된 상품 30개 출력
(고려중 - 출력 순서 선택 : 등록순/재고량순..)

**Comment by rosd89** [comment]
실패
