### ISSUE TITLE
[choiminji][#5F4B8B - 상품 진열 공간] 상품의 상태(ice-hot) 선택

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#40]
[기능] 상품은 ice와 hot 두 가지 상태를 선택할 수 있다

[소요시간] 30분

[완료조건] 
상품 등록 시 적용된 값에 따라 진열대에 표시됨
(default 값은 ice로 등록되나, 상품 등록 시 선택 가능)

**Comment by rosd89** [comment]
실패
