### ISSUE TITLE
[choiminji][#5F4B8B - 자판기의 상태] 상품 판매 가능 여부 표시

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#41]
[기능] 자판기는 출력 여부에 체크된 상품에 한하여, 재고량에 따라 품절 상태를 표시한다

[소요시간] 1시간

[완료조건] 
출력여부에 체크된 상품 한정, 재고랑 0일 경우 품절 상태 표기

**Comment by rosd89** [comment]
실패
