### ISSUE TITLE
[choiminji][#5F4B8B - 상품 선택 버튼] 상품의 판매 가능 여부 판단하여 활성화

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#43]
[기능] 상품의 판매 가능 여부를 판단하여 활성화 여부를 표기한다

[소요시간] 1시간

[완료조건]
품절 상품일 경우 버튼 비활성화
입력받은 재화 금액과 상품의 가격 비교하여, 재화 금액 > 상품 가격일 경우 활성화 / 재화 금액 < 상품 가격일 경우 비활성화

**Comment by rosd89** [comment]
실패
