### ISSUE TITLE
[choiminji][#5F4B8B - 잔돈 반환] 상품 결제 5초 경과 후 남은 재화 반환

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#46]
[기능] 상품 결제가 완료된 후, 5초가 지나면 남은 재화를 반환한다

[소요시간] 1시간

[완료조건]
남은 재화를 파악하여 상품 반환 5초 후 사용자에게 반환

**Comment by rosd89** [comment]
실패
