### ISSUE TITLE
[choiminji][#5F4B8B - 잔돈 반환] 결제 5초 경과 이전 새로운 상품 선택 시 리셋

### ISSUE THREAD

**Issue by mmindy** [rosd89/the-colors#47]
[기능] 결제 완료 5초 경과 이전에 새로운 상품을 선택할 수 있다

[소요시간] 1시간

[완료조건]
5초 이전 상품 선택 버튼 입력 시, 결제 프로세스로 복귀
재화 반환 프로세스 무효화

**Comment by rosd89** [comment]
실패
