### ISSUE TITLE
[duckhee][#5F4B8B - 상품 등록] 상품명, 가격, 재고량 상품 등록

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#6]
- [기능]
	- 필요한 속성들을 가진 상품을 생성해 등록
- [완료조건]
	- 상품명, 가격, 재고량, 판매재고량, 판매가능유무 속성을 가진 상품 등록
	- 등록된 상품 확인
- [예상소요시간]
	- 4시간

**Comment by shldhee** [comment]
[완료시간]
1시간 30분

**Comment by shldhee** [comment]
[수정시간]
1시간

**Comment by rosd89** [comment]
실패
