### ISSUE TITLE
[duckhee][#5F4B8B - 상품 등록] 상품 등록 시 중복된 상품 있는지 확인

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#7]
- [기능]
	- 상품 속성 중 이름을 비교하여 같은 상품인지 확인 후 등록
- [완료조건]
	- 같은 상품명으로 등록해보고 같은 상품일 경우 경고창 표시
- [예상소요시간]
	- 2시간

**Comment by rosd89** [comment]
실패
