### ISSUE TITLE
[duckhee][#5F4B8B - 상품 등록] 상품 삭제

### ISSUE THREAD

**Issue by shldhee** [rosd89/the-colors#8]
- [기능]
	- 상품 속성 중 이름을 입력해 해당 상품을 삭제
- [완료조건]
	- 상품명으로 삭제 시 모든 데이터 사라짐
- [예상소요시간]
	- 2시간

**Comment by shldhee** [comment]
[완료시간]
30분

**Comment by rosd89** [comment]
실패
